name: "model_init"
backend: "python"
max_batch_size: 1
input [
  {
    name: "input_args",
    data_type: TYPE_STRING,
    dims: [ -1 ]
  }
]
output [
  {
    name: "output_message",
    data_type: TYPE_STRING,
    dims: [ -1 ]
  }
]
instance_group [
  {
    kind: KIND_CPU
  }
]
